// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umbral.Infrastructure.Persistence;

#nullable disable

namespace Umbral.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UmbralDbContext))]
    [Migration("20260529014100_DropUsuariosAuth")]
    partial class DropUsuariosAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Umbral.Domain.CatalogoBusquedaTesoro.Mision.Etapa", b =>
                {
                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoQRSolucion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("codigo_qr_solucion");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("MisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("EtapaId");

                    b.HasIndex("MisionId", "Orden")
                        .IsUnique();

                    b.ToTable("etapas", (string)null);
                });

            modelBuilder.Entity("Umbral.Domain.CatalogoBusquedaTesoro.Mision.Mision", b =>
                {
                    b.Property<Guid>("MisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("MisionId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("misiones", (string)null);
                });

            modelBuilder.Entity("Umbral.Domain.CatalogoBusquedaTesoro.Mision.Pista", b =>
                {
                    b.Property<Guid>("PistaId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contenido");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<int?>("SegundosLiberacion")
                        .HasColumnType("integer")
                        .HasColumnName("segundos_liberacion");

                    b.Property<string>("TipoLiberacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_liberacion");

                    b.HasKey("PistaId");

                    b.HasIndex("EtapaId");

                    b.ToTable("pistas", (string)null);
                });

            modelBuilder.Entity("Umbral.Domain.Sesion.EquipoSesion", b =>
                {
                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("codigo_acceso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_total");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("EquipoId");

                    b.HasIndex("SesionId", "Nombre")
                        .IsUnique();

                    b.ToTable("equipos_sesion", (string)null);
                });

            modelBuilder.Entity("Umbral.Domain.Sesion.EventoSesion", b =>
                {
                    b.Property<Guid>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("EventoId");

                    b.HasIndex("SesionId", "OcurridoEn");

                    b.ToTable("eventos_sesion", (string)null);
                });

            modelBuilder.Entity("Umbral.Domain.Sesion.Evidencia", b =>
                {
                    b.Property<Guid>("EvidenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoQR")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("codigo_qr_leido");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resultado");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<DateTime>("TimestampServidor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_servidor");

                    b.HasKey("EvidenciaId");

                    b.HasIndex("SesionId");

                    b.ToTable("evidencias", (string)null);
                });

            modelBuilder.Entity("Umbral.Domain.Sesion.Sesion", b =>
                {
                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FinalizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalizada_en");

                    b.Property<DateTime>("IniciadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciada_en");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_id");

                    b.Property<string>("TipoSesion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_sesion");

                    b.HasKey("SesionId");

                    b.ToTable("sesiones", (string)null);
                });

            modelBuilder.Entity("Umbral.Domain.CatalogoBusquedaTesoro.Mision.Etapa", b =>
                {
                    b.HasOne("Umbral.Domain.CatalogoBusquedaTesoro.Mision.Mision", null)
                        .WithMany("_etapas")
                        .HasForeignKey("MisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.Domain.CatalogoBusquedaTesoro.Mision.Pista", b =>
                {
                    b.HasOne("Umbral.Domain.CatalogoBusquedaTesoro.Mision.Etapa", null)
                        .WithMany("_pistas")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.Domain.Sesion.EquipoSesion", b =>
                {
                    b.HasOne("Umbral.Domain.Sesion.Sesion", null)
                        .WithMany("_equipos")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.Domain.Sesion.EventoSesion", b =>
                {
                    b.HasOne("Umbral.Domain.Sesion.Sesion", null)
                        .WithMany("_historialEventos")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.Domain.Sesion.Evidencia", b =>
                {
                    b.HasOne("Umbral.Domain.Sesion.Sesion", null)
                        .WithMany("_evidencias")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbral.Domain.Sesion.Sesion", b =>
                {
                    b.OwnsOne("Umbral.Domain.Sesion.ContextoBusquedaTesoro", "ContextoBT", b1 =>
                        {
                            b1.Property<Guid>("SesionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EtapaActualIndex")
                                .HasColumnType("integer")
                                .HasColumnName("etapa_actual_index");

                            b1.Property<Guid?>("GanadorEtapaActualId")
                                .HasColumnType("uuid")
                                .HasColumnName("ganador_etapa_actual_id");

                            b1.Property<string>("MisionSnapshot")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("mision_snapshot_json");

                            b1.HasKey("SesionId");

                            b1.ToTable("contextos_bt", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SesionId");
                        });

                    b.Navigation("ContextoBT");
                });

            modelBuilder.Entity("Umbral.Domain.CatalogoBusquedaTesoro.Mision.Etapa", b =>
                {
                    b.Navigation("_pistas");
                });

            modelBuilder.Entity("Umbral.Domain.CatalogoBusquedaTesoro.Mision.Mision", b =>
                {
                    b.Navigation("_etapas");
                });

            modelBuilder.Entity("Umbral.Domain.Sesion.Sesion", b =>
                {
                    b.Navigation("_equipos");

                    b.Navigation("_evidencias");

                    b.Navigation("_historialEventos");
                });
#pragma warning restore 612, 618
        }
    }
}
