services:

  postgres:
    image: postgres:16-alpine
    container_name: umbral_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-umbral_db}
      POSTGRES_USER: ${POSTGRES_USER:-umbral_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-umbral_pass}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umbral_user -d umbral_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - umbral_net

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: umbral_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-umbral_user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-umbral_pass}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - umbral_net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: umbral_keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HEALTH_ENABLED: "true"
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import:ro
    networks:
      - umbral_net

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: umbral_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=umbral_db;Username=umbral_user;Password=umbral_pass"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: umbral_user
      RabbitMQ__Password: umbral_pass
      Keycloak__Authority: "http://keycloak:8080/realms/umbral"
      Keycloak__Audience: umbral-api
      Keycloak__RequireHttpsMetadata: "false"
      KeycloakAdmin__BaseUrl: "http://keycloak:8080"
      KeycloakAdmin__Realm: umbral
      KeycloakAdmin__UseDevStub: "false"
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - umbral_net
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    container_name: umbral_gateway
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8000
      ReverseProxy__Clusters__umbral-api__Destinations__api__Address: "http://api:5000/"
    ports:
      - "8000:8000"
    depends_on:
      - api
    networks:
      - umbral_net
    restart: unless-stopped

volumes:
  postgres_data: {}
  rabbitmq_data: {}

networks:
  umbral_net: {}
